import Link from "next/link";
import styles from "../styles/Eliza.module.css";
import "../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className={styles.appHeader}>
          <h1 className={styles.headline}>Connect with Next.js</h1>
          <h4 className={styles.subtitle}>
            React Server Components with Server actions
          </h4>
          <div className={styles.links}>
            Choose an example:
            <Link href="/">Unary Calls</Link>
            <Link href="/server-streaming">Server Streaming Calls</Link>
            <Link href="/ssr">SSR</Link>
            <Link href="/new">React Server Components with Server actions</Link>
          </div>
        </header>
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
